//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminvereinbarungLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerminvereinbarungModelContainer : DbContext
    {
        public TerminvereinbarungModelContainer()
            : base("name=TerminvereinbarungModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Behandlung> BehandlungSet { get; set; }
        public virtual DbSet<Termin> TerminSet { get; set; }
        public virtual DbSet<Zeitslot> ZeitslotSet { get; set; }
    }
}
