
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TerminvereinbarungLib
{

using System;
    using System.Collections.Generic;
    
public partial class Termin
{

    public int Id { get; set; }

    public int ArztId { get; set; }

    public int PatientId { get; set; }

    public bool angefragt { get; set; }

    public bool bestätigt { get; set; }

    public bool abgeschlossen { get; set; }

    public int BehandlungId { get; set; }

    public int ZeitslotId { get; set; }



    public virtual User Arzt { get; set; }

    public virtual User Patient { get; set; }

    public virtual Behandlung Behandlung { get; set; }

    public virtual Zeitslot Zeitslot { get; set; }

}

}
